menu:
  home: /
  archives: /archives
  Node.js: /node
  books: /hexo
  
submenu:
  rss: /atom.xml
  customization: /customization
  about: /about

menu_icon:
  home: home
  archives: archive
  Node.js: book
  books: book
  about: user
  rss: rss
  customization: question-circle

widgets:
# - search
- category
- weixin
- calendar
- links
# - tagcloud
# - tag
- archive
# - weibo

excerpt_link: Read More
comment_link: Comments

# header头像
avatar: /img/default/avatar.png
# header右侧图片展示
ad: 

# 百度分享
baidu_share: true

# 请到after_footer.ejs中替换百度统计代码
baidu_tongji: true

# 微博: height小挂件高度；url替换成自己的微博挂件地址，同步修改url中height的值
weibo:
  height: 600
  url: http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=600&fansRow=1&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=1&isFans=0&uid=1934606495&verifier=a6769878&dpc=1

# Calendar
calendar:
  language: zh-CN
  root: calendar

# weixin
weixin:
  qrcode: /img/default/qrcode.jpg
  alt: 欢迎关注个人公众账号

# links
links:
  晓晓博客: http://xiaoyun.farbox.com
  图灵社区: http://www.ituring.com.cn/users/136808

# farbox
fancybox: true

# resume
resume_photo: /assets/img/resume/resume.jpg
resume:
  name: 鲁 鹏
  birth: 1989年5月
  nation: 汉族
  political_status: 中共党员
  birth_place: 湖北省武汉市
  domicile_place: 北京市
  address: 北京市房山区北京理工大学良乡校区
  postcode: 102488
  email: decadent_prince@foxmail.com
  phone: 18511xxxxxx
  
  