menu:
  home: /
  archives: /archives
  Node.js: /node
  books: /hexo
  

submenu:
  rss: /atom.xml
  customization: /customization
  about: /about

menu_icon:
  home: home
  archives: archive
  Node.js: book
  books: book
  about: user
  rss: rss
  customization: question-circle

widgets:
# - search
- category
- weixin
- calendar
- links
- tagcloud
# - tag
- archive
# - weibo

excerpt_link: Read More
comment_link: Comments

# header头像
avatar: /img/default/avatar.png
# header右侧图片展示
ad: 

# 百度分享
baidu_share: true

# 请到baidu_tongji.ejs中替换代码
baidu_tongji: true

# height小挂件高度；url替换成自己的微博挂件地址，同步修改url中height的值
weibo:
  height: 600
  url: 

# 评论提供可以选择 duoshuo 或者 wumii，无需评论，此处不填就行。
comment_provider: wumii
# 关联推荐提供可以选择baidu_tuijian 或者 wumii, 无需关联推荐，此处不填即可。
relate_provider: baidu_tuijian

# 多说，填写多说short_name
duoshuo_short_name: lupeng-test

# wumii，填写网站域名，例如：http://lupeng.me
wumii_siteprefix: http://lupeng.me

# 百度推荐，填写百度推荐ID，例如我的是：hm_t_88638
baidu_tuijian_id: 

# Calendar
calendar:
  language: zh-CN
  root: calendar

# weixin
weixin:
  qrcode: /img/default/qrcode.jpg
  alt: 欢迎关注，该账号供个人学习使用，偶尔做一些开发尝试，更新频率较低。

# farbox
fancybox: true